### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by BeiNing-Z** [ExtremeFLOW/neko#1093]
When I execute make
The following error occurs:
NVFORTRAN-S-0038-Symbol, bge, has not been explicitly declared (common/signal.f90: 91)
  0 inform,   0 warnings,   1 severes, 0 fatal for signal_usr
when compiling with the following configure:
./configure --prefix=INSTALL_DIR --with-cuda=/opt/nvidia/hpc_sdk/Linux_x86_64/23.11/cuda/ CUDA_CFLAGS=-O3  CUDA_ARCH=-arch=sm_70  NVCC=/opt/nvidia/hpc_sdk/Linux_x86_64/23.11/compilers/bin/nvcc --enable-device-mpi
mpif90 version is
nvfortran 23.11-0 64-bit target on x86-64 Linux -tp cascadelake
NVIDIA Compilers and Tools
Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

and I have already used the 
git apply patches/nvhpc_bge.patch

fatal: can't open patch 'patches/nvhpc_bge.patch': No such file or directory

my neko version is 0.7.0

Could you please help me to figure out what's wrong with signal.f90?
I will fully appreciate it.

**Comment by BeiNing-Z** [comment]
Could you please help me to figure out what's wrong with signal.f90?
I will fully appreciate it.

**Comment by njansson** [comment]
Given the error message, this seems to be from the 0.7.0 release distribution, which due to an error in the distribution script does not include the patches.

This will be fixed in the next, bug fix for 0.7 and the next major release.

Until then, the patch for 0.7 can be found here:
https://github.com/ExtremeFLOW/neko/blob/release/0.7/patches/nvhpc_bge.patch
